version: "3"

networks:
  company-service-net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: on-failure
    networks:
      - company-service-net

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: companyDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cretP@ss
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - company-service-net

volumes:
  data:
