version: "3"

networks:
  company-service-net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - kafka
    restart: on-failure
    networks:
      - company-service-net

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: companyDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cretP@ss
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - company-service-net

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

volumes:
  data:
